<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Conceptos-básicos" data-toc-modified-id="Conceptos-básicos-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Conceptos básicos</a></span></li><li><span><a href="#Creación-de-algunos-arreglos-clásicos" data-toc-modified-id="Creación-de-algunos-arreglos-clásicos-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creación de algunos arreglos clásicos</a></span></li><li><span><a href="#Operaciones-elementales" data-toc-modified-id="Operaciones-elementales-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operaciones elementales</a></span></li><li><span><a href="#Operaciones-especiales" data-toc-modified-id="Operaciones-especiales-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operaciones especiales</a></span><ul class="toc-item"><li><span><a href="#Operaciones-entre-matrices-de-diferente-tamaño-(Broadcasting)" data-toc-modified-id="Operaciones-entre-matrices-de-diferente-tamaño-(Broadcasting)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Operaciones entre matrices de diferente tamaño (Broadcasting)</a></span></li></ul></li><li><span><a href="#Módulo-de-álgebra-lineal" data-toc-modified-id="Módulo-de-álgebra-lineal-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Módulo de álgebra lineal</a></span><ul class="toc-item"><li><span><a href="#Más-matrices-especiales" data-toc-modified-id="Más-matrices-especiales-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Más matrices especiales</a></span></li></ul></li><li><span><a href="#Módulo-linalg" data-toc-modified-id="Módulo-linalg-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Módulo <code>linalg</code></a></span></li><li><span><a href="#Una-primera-aplicación" data-toc-modified-id="Una-primera-aplicación-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Una primera aplicación</a></span></li></ul></div>

# Paquete Numpy

*Carlos Isaac Zainea Maya*


[Numpy](https://numpy.org/) es la librería central para la computación científica en Python, nos permite acceder a una gran cantidad de funciones matemáticas y crear arreglos multidimensionales de alta eficiencia. Es un paquete facil de utilizar y posee una de las [documentaciones](https://numpy.org/doc/) más robustas de Python, quizás es uno de los paquetes más usados.  Su ancestro es un paquete llamado Numeric, creado por [Jim Hugunin](https://en.wikipedia.org/wiki/Jim_Hugunin) y en 2005, con la incorporación de Numarray y varias modificaciones, [Travis Oliphant](https://en.wikipedia.org/wiki/Travis_Oliphant) lo transforma en Numpy.

In [1]:
5**(1/2)

2.23606797749979

In [2]:
import math 

In [3]:
math.pi

3.141592653589793

In [4]:
import math as loquequiera

In [5]:
loquequiera.pi

3.141592653589793

In [6]:
?math.pi

In [7]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [8]:
import numpy as np

In [9]:
?np

In [10]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


## Conceptos básicos

El objeto más importante de numpy es el arreglo multidimensional homogéneo, es decir, una tabla de elementos del mismo tipo, indexados por una tupla de enteros no negativos. En numpy las dimensiones del arreglo las llamaremos ejes (axes).

**Ejemplo**

Un elemento en $\mathbb{R}^n$ es un arreglo $n$-dimensional con un solo eje:



In [11]:
V=np.array([2,1,4])
print(V)

[2 1 4]


In [12]:
V=np.array([2,1,4])
W=np.array([3,1,2])

In [13]:
print(V+W)

[5 2 6]


In [14]:
BV=np.array([True,False,True])
print(BV)

[ True False  True]


Una matriz de tamaño $n\times m$ es un arreglo de dos ejes:

In [15]:
M=np.array([[1,0,1],[0,1,0],[2,1,3]])
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [16]:
M.dtype

dtype('int64')

In [17]:
M.shape

(3, 3)

In [18]:
CS=M.cumsum()

En casos más generales podriamos definir un tensor:

In [19]:
T=np.array([[[[1,2,1,4],[3,2,4,1],[4,2,3,1]],[[1,2,3,1],[0,1,2,3],[1,4,5,6]]],[[[2,3,4,1],[1,1,2,1],[0,1,1,2]],[[1,2,3,1],[0,1,1,1],[2,1,3,1]]]])
print(T)

[[[[1 2 1 4]
   [3 2 4 1]
   [4 2 3 1]]

  [[1 2 3 1]
   [0 1 2 3]
   [1 4 5 6]]]


 [[[2 3 4 1]
   [1 1 2 1]
   [0 1 1 2]]

  [[1 2 3 1]
   [0 1 1 1]
   [2 1 3 1]]]]


In [20]:
T.shape

(2, 2, 3, 4)

In [21]:
T.dtype

dtype('int64')

In [22]:
T.ndim

4

La exploración de elementos que conforman al arreglo es similar a la de las listas de Python, con la salvedad de que en la matriz, o el tensor no tengo una lista de listas:

In [23]:
V

array([2, 1, 4])

In [24]:
V[1]

1

In [25]:
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [26]:
M[1,1]

1

In [27]:
M[1][1]

1

In [28]:
print(T)

[[[[1 2 1 4]
   [3 2 4 1]
   [4 2 3 1]]

  [[1 2 3 1]
   [0 1 2 3]
   [1 4 5 6]]]


 [[[2 3 4 1]
   [1 1 2 1]
   [0 1 1 2]]

  [[1 2 3 1]
   [0 1 1 1]
   [2 1 3 1]]]]


In [29]:
T[1]

array([[[2, 3, 4, 1],
        [1, 1, 2, 1],
        [0, 1, 1, 2]],

       [[1, 2, 3, 1],
        [0, 1, 1, 1],
        [2, 1, 3, 1]]])

In [30]:
T[1,0]

array([[2, 3, 4, 1],
       [1, 1, 2, 1],
       [0, 1, 1, 2]])

In [31]:
T[1,0,2]

array([0, 1, 1, 2])

In [32]:
TT=np.array([[[1,0,1],[0,1,0]],[[1,"0",3],[1,2,5]]])

In [33]:
TT

array([[['1', '0', '1'],
        ['0', '1', '0']],

       [['1', '0', '3'],
        ['1', '2', '5']]], dtype='<U21')

In [34]:
TT.shape

(2, 2, 3)

In [35]:
TT[1][1][1]

'2'

Podemos usar también índices de sublistas

In [36]:
M2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
M2[:2,1:3]

array([[2, 3],
       [6, 7]])

In [38]:
T=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32],[33,34,35,36]]])
print(T)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [39]:
T[:2,1:,1:3]

array([[[ 6,  7],
        [10, 11]],

       [[18, 19],
        [22, 23]]])

También podemos extraer elementos utilizando listas

In [40]:
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
M2[[0,2],[1,3]]

array([ 2, 12])

In [42]:
M2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
M2[[0,1,2,1],[0,1,2,3]]

array([ 1,  6, 11,  8])

In [44]:
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
M2[:,[0,1,2,2,1,1,2,2]]

array([[ 1,  2,  3,  3,  2,  2,  3,  3],
       [ 5,  6,  7,  7,  6,  6,  7,  7],
       [ 9, 10, 11, 11, 10, 10, 11, 11]])

Extraer filas

In [46]:
M2[np.array([0,2])]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Extraer columnas

In [47]:
M2[:,np.array([2,0])]

array([[ 3,  1],
       [ 7,  5],
       [11,  9]])

Algunos comandos elementales son:

* `.ndim` (número de ejes del arreglo)

In [48]:
V.ndim

1

In [49]:
M.ndim

2

In [50]:
T.ndim

3

* `.shape` (La dimensión del arreglo. Obtenemos una tupla de enteros)

In [51]:
V.shape

(3,)

In [52]:
M.shape

(3, 3)

In [53]:
T.shape

(3, 3, 4)

* `.size` (El número total de elementos que conforman al arreglo)

In [54]:
V.size

3

In [55]:
T.size

36

In [56]:
M.size

9

In [57]:
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [58]:
np.concatenate((M,M),axis=1)

array([[1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [2, 1, 3, 2, 1, 3]])

In [59]:
np.array([[0],[0],[0]])

array([[0],
       [0],
       [0]])

In [60]:
np.array([    0,0,0])

array([0, 0, 0])

In [61]:
N=np.concatenate((M,np.array([[0],[0],[0]])),axis=1)
N

array([[1, 0, 1, 0],
       [0, 1, 0, 0],
       [2, 1, 3, 0]])

In [62]:
N[:,[0,1,3,2]]

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [2, 1, 0, 3]])

* `.dtype` (el tipo de lementos en el arreglo)

In [63]:
M.dtype

dtype('int64')

In [64]:
A=np.array([3<2,2<3,4<5])
print(A)

[False  True  True]


In [65]:
A.dtype

dtype('bool')

In [66]:
TT2=np.array([A,V])
print(TT2)

[[0 1 1]
 [2 1 4]]


In [67]:
TT2.dtype

dtype('int64')

## Creación de algunos arreglos clásicos

Tenemos la oportunidad de utilizar algunas funciones de Numpy para generar arreglos y matrices conocidas:


In [68]:
ceros=np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [69]:
unos=np.ones((2,2,3))
print(unos)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [70]:
constante=np.full((4,3),5)
print(constante)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [71]:
constante2=np.full((4,3),5<2)
constante2[1,1]=True
print(constante2)

[[False False False]
 [False  True False]
 [False False False]
 [False False False]]


In [72]:
constante3=np.full((4,3),"Hola")
print(constante3)

[['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']]


In [73]:
identidad=np.eye(6,5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [74]:
aleatoria = np.random.random((2,2))  
print(aleatoria) 

[[0.56735597 0.89544819]
 [0.73206181 0.8958083 ]]


In [75]:
?np.random

## Operaciones elementales

Podemos hacer operaciones matriciales elementales:

In [76]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
y = np.array([[7,8,9],[9,8,7]])
z=np.array([[1,1],[2,1]])

In [77]:
print(x)
print(y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[7 8 9]
 [9 8 7]]
[[1 1]
 [2 1]]


In [78]:
print(x + y)

[[ 8. 10. 12.]
 [13. 13. 13.]]


In [79]:
print(x - y)

[[-6. -6. -6.]
 [-5. -3. -1.]]


In [80]:
print(x*y) #multiplicación elemento a elemento

[[ 7. 16. 27.]
 [36. 40. 42.]]


In [81]:
print(x / y) #división elemento a elemento

[[0.14285714 0.25       0.33333333]
 [0.44444444 0.625      0.85714286]]


In [82]:
print(y)
print(np.sqrt(y))  #raíz cuadrada elemento a elemento

[[7 8 9]
 [9 8 7]]
[[2.64575131 2.82842712 3.        ]
 [3.         2.82842712 2.64575131]]


In [83]:
print(np.transpose(y)) #transpuesta

[[7 9]
 [8 8]
 [9 7]]


In [84]:
print(y.T) #transpuesta

[[7 9]
 [8 8]
 [9 7]]


(m,k) @ (k,n)=(m,n)

In [85]:
print(x@np.transpose(y)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [86]:
print(np.transpose(y)@x)

[[43. 59. 75.]
 [40. 56. 72.]
 [37. 53. 69.]]


In [87]:
print(x.dot(y.T)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [88]:
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [89]:
print(np.sum(x))   #suma de todos los elementos
print(np.sum(x, axis=0))  #suma de elementos por columnas
print(np.sum(x, axis=1))   #suma de elementos por filas

21.0
[5. 7. 9.]
[ 6. 15.]


Mas funciones [aquí](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

## Operaciones especiales

En ocasiones tenemos que hacer algunas operaciones que no tienen en cuenta la forma de las matrices o que involucran matrices de diferentes tamaños. Aquí algunos ejemplos:

In [90]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [91]:
print(x+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [92]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array(np.transpose([[1, 0, 1,1]]))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1]
 [0]
 [1]
 [1]]


In [93]:
x+v

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [94]:
x+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

* Suma de un vector a una fila

In [95]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [96]:
x[0]=x[0]+v
print(x)

[[ 2  2  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Multiplicar una fila por escalar

In [97]:
x[0]=x[0]*2
print(x)

[[ 4  4  8]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Intercambiar filas

In [98]:
fc=x.copy()
x[1]=x[0]
x[0]=fc[1]
print(x)


[[ 4  5  6]
 [ 4  4  8]
 [ 7  8  9]
 [10 11 12]]


### Operaciones entre matrices de diferente tamaño (Broadcasting)

NumPy transforma los arreglos involucrados para que tengan el mismo tamaño y, por tanto, puedan someterse a las operaciones por elementos sin generar excepciones.

In [99]:
a = np.arange(0.2, 40.2, 10.5)
a.shape

(4,)

In [100]:
print(a)

[ 0.2 10.7 21.2 31.7]


In [101]:
a = a[:, np.newaxis]  #Adicionamos un eje
print(a.shape)
a

(4, 1)


array([[ 0.2],
       [10.7],
       [21.2],
       [31.7]])

In [102]:
b = np.array([0, 1, 2])
print(b)

[0 1 2]


In [103]:
a+b

array([[ 0.2,  1.2,  2.2],
       [10.7, 11.7, 12.7],
       [21.2, 22.2, 23.2],
       [31.7, 32.7, 33.7]])

In [104]:
A=np.array([[0,1],[1,2]])
B=np.array([[2,1],[1,2]])

In [105]:
A= A[:,:, np.newaxis] 

In [106]:
A

array([[[0],
        [1]],

       [[1],
        [2]]])

In [107]:
A+B

array([[[2, 1],
        [2, 3]],

       [[3, 2],
        [3, 4]]])

## Módulo de álgebra lineal



### Más matrices especiales

Tenemos la posibilidad de buscar más matrices interesantes en Numpy.

* Matriz triangular

In [108]:
A=np.random.random((5,5))
print(A)

[[0.35824789 0.67021058 0.3197765  0.2886132  0.25215637]
 [0.53465983 0.56457067 0.03976936 0.3170706  0.43055555]
 [0.04561354 0.46668975 0.34750522 0.33989928 0.87062758]
 [0.23180803 0.35446253 0.43447627 0.11963124 0.078807  ]
 [0.89015904 0.86531812 0.08071032 0.53489887 0.01239648]]


In [109]:
np.triu(A)

array([[0.35824789, 0.67021058, 0.3197765 , 0.2886132 , 0.25215637],
       [0.        , 0.56457067, 0.03976936, 0.3170706 , 0.43055555],
       [0.        , 0.        , 0.34750522, 0.33989928, 0.87062758],
       [0.        , 0.        , 0.        , 0.11963124, 0.078807  ],
       [0.        , 0.        , 0.        , 0.        , 0.01239648]])

In [110]:
np.triu(A,1)

array([[0.        , 0.67021058, 0.3197765 , 0.2886132 , 0.25215637],
       [0.        , 0.        , 0.03976936, 0.3170706 , 0.43055555],
       [0.        , 0.        , 0.        , 0.33989928, 0.87062758],
       [0.        , 0.        , 0.        , 0.        , 0.078807  ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [111]:
np.triu(A,-1)

array([[0.35824789, 0.67021058, 0.3197765 , 0.2886132 , 0.25215637],
       [0.53465983, 0.56457067, 0.03976936, 0.3170706 , 0.43055555],
       [0.        , 0.46668975, 0.34750522, 0.33989928, 0.87062758],
       [0.        , 0.        , 0.43447627, 0.11963124, 0.078807  ],
       [0.        , 0.        , 0.        , 0.53489887, 0.01239648]])

In [112]:
np.triu(np.ones((3,3)),2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [113]:
M3=(a+b).T
print(M3)

[[ 0.2 10.7 21.2 31.7]
 [ 1.2 11.7 22.2 32.7]
 [ 2.2 12.7 23.2 33.7]]


In [114]:
np.triu(M3)

array([[ 0.2, 10.7, 21.2, 31.7],
       [ 0. , 11.7, 22.2, 32.7],
       [ 0. ,  0. , 23.2, 33.7]])

In [115]:
np.tril(M3)

array([[ 0.2,  0. ,  0. ,  0. ],
       [ 1.2, 11.7,  0. ,  0. ],
       [ 2.2, 12.7, 23.2,  0. ]])

In [116]:
np.tril(M3,-1)

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 1.2,  0. ,  0. ,  0. ],
       [ 2.2, 12.7,  0. ,  0. ]])

* Matriz diagonal

In [117]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [118]:
print(A)

[[0.35824789 0.67021058 0.3197765  0.2886132  0.25215637]
 [0.53465983 0.56457067 0.03976936 0.3170706  0.43055555]
 [0.04561354 0.46668975 0.34750522 0.33989928 0.87062758]
 [0.23180803 0.35446253 0.43447627 0.11963124 0.078807  ]
 [0.89015904 0.86531812 0.08071032 0.53489887 0.01239648]]


In [119]:
A.diagonal()

array([0.35824789, 0.56457067, 0.34750522, 0.11963124, 0.01239648])

## Módulo `linalg` 

Numpy tiene un módulo especializado en funciones de [álgebra lineal](https://numpy.org/doc/stable/reference/routines.linalg.html)

* Potencias de matrices

In [120]:
N = np.array([[1, 0, 1], [2, -1, 3], [4, 3, 2]])
print(N)
np.linalg.matrix_power(N,2)

[[ 1  0  1]
 [ 2 -1  3]
 [ 4  3  2]]


array([[ 5,  3,  3],
       [12, 10,  5],
       [18,  3, 17]])

* Determinantes



In [121]:
np.linalg.det(N)

-1.0000000000000009

* Valores y vectores propios

In [122]:
np.linalg.eig(N)

(array([ 4.84625207,  0.070739  , -2.91699107]),
 array([[ 0.21740883,  0.64484788, -0.15390745],
        [ 0.50347557, -0.47443887, -0.78286616],
        [ 0.83620915, -0.59923199,  0.60285411]]))

* Rango

In [123]:
np.linalg.matrix_rank(N)

3

* Solución de sistemas de ecuaciones lineales

In [124]:
np.linalg.solve(N, [1,2,3])

array([ 2., -1., -1.])

In [125]:
print(N)

[[ 1  0  1]
 [ 2 -1  3]
 [ 4  3  2]]


* Matrices Inversas



In [126]:
Ninv=np.linalg.inv(N)
Ninv

array([[ 11.,  -3.,  -1.],
       [ -8.,   2.,   1.],
       [-10.,   3.,   1.]])

Comprobamos este resultado:

In [127]:
Ninv @ N

array([[ 1.00000000e+00,  9.99200722e-16, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11022302e-15,  1.00000000e+00]])

Observe que la anterior es la matriz idéntica.

In [128]:
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [129]:
?np.trace

# Herramientas interactivas `ipywidgets`

Otro paquete que será transversal en este curso y nos permitira crear interfaces interesantes para nuestros estudiantes es [ipywidgets`](https://ipywidgets.readthedocs.io/en/stable/). Para instalar desde el cuaderno escriba:

In [130]:
!pip install ipywidgets

In [131]:
 pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [132]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


Importemos el paquete

In [133]:
from ipywidgets import interact
import ipywidgets as widgets

La herramienta más básica de este paquete es la función `interact`. En el siguiente ejemplo veamos su utilidad:

In [134]:
def f(x):
    print("El valor que escogió es", x)
    return x

In [135]:
f(4)

El valor que escogió es 4


4

In [136]:
def f(x):
    y=x+5
    print(x,"+",5,"=",y)
    return y

In [137]:
f(8)

8 + 5 = 13


13

In [138]:
def nombrelargoocorto(t):
    if len(t)>=7:
        print(t+" es un nombre muy largo")
        z="largo"
    else:
        print(t+" es un nombre corto")
        z="corto"
    return z

In [139]:
nombrelargoocorto("Benjamin")

Benjamin es un nombre muy largo


'largo'

In [140]:
def f(x):
    y=x+5
    print(x,"+",5,"=",y)
    return y

In [141]:
interact(f, x=1.2)

interactive(children=(FloatSlider(value=1.2, description='x', max=3.5999999999999996, min=-1.2), Output()), _d…

<function __main__.f(x)>

In [142]:
interact(nombrelargoocorto, t="Isaac")

interactive(children=(Text(value='Isaac', description='t'), Output()), _dom_classes=('widget-interact',))

<function __main__.nombrelargoocorto(t)>

In [143]:
def f(x):
    print("El valor que escogió es", x)
    return x

In [144]:
interact(f, x=True)

interactive(children=(Checkbox(value=True, description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.f(x)>

In [145]:
interact(f, x={0:'Elemento 1',1:'Elemento 2'})

interactive(children=(Dropdown(description='x', options={0: 'Elemento 1', 1: 'Elemento 2'}, value='Elemento 1'…

<function __main__.f(x)>

In [146]:
interact(f, x='Soy interactivo')

interactive(children=(Text(value='Soy interactivo', description='x'), Output()), _dom_classes=('widget-interac…

<function __main__.f(x)>

Los elementos que permiten la interacción con el usuario son los widgets, una lista completa de ellos se encuentra [aquí.](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html)

A continuación hacemos un cambio sobre el widget:

In [147]:
interact(f, x=widgets.IntText(
    value=7,
    description='Escriba un número: ',
    disabled=False
));

interactive(children=(IntText(value=7, description='Escriba un número: '), Output()), _dom_classes=('widget-in…

## Una primera aplicación

Ya que conocemos algo de Numpy y ipywidgets vamos a crear un ejemplo muy sencillo para calcular algunos estadísticos elementales de una lista de valores:

In [148]:
def estadisticos(x):
    L=x.split()
    L=[float(i) for i in L]        
    x=np.array(list(L))
    print("La media es", np.mean(x))
    print("La mediana es", np.median(x))
    print("La varianza poblacional es", np.var(x))
    print("La varianza muestral es", np.var(x,ddof=1))
    print("La desviación estándar poblacional es", np.std(x))
    print("La desviación estándar muestral es", np.std(x,ddof=1))
    return

In [149]:
estadisticos("1 2 3")

La media es 2.0
La mediana es 2.0
La varianza poblacional es 0.6666666666666666
La varianza muestral es 1.0
La desviación estándar poblacional es 0.816496580927726
La desviación estándar muestral es 1.0


Evalue los estadísticos del conjunto de datos [1,1,2,3] y compruebelo con la herramienta:

In [150]:
estadisticos("1 2 3 4 5 7 8 3 1 3 4 1 3 4 8 0 9")

La media es 3.8823529411764706
La mediana es 3.0
La varianza poblacional es 6.927335640138407
La varianza muestral es 7.360294117647058
La desviación estándar poblacional es 2.6319832142584816
La desviación estándar muestral es 2.7129861993100994


In [151]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

In [152]:
def estadisticos(x):
    try:
        L=x.split()
        L=[float(i) for i in L]        
        x=np.array(list(L))
        print("La media es", np.mean(x))
        print("La mediana es", np.median(x))
        print("La varianza poblacional es", np.var(x))
        print("La varianza muestral es", np.var(x,ddof=1))
        print("La desviación estándar poblacional es", np.std(x))
        print("La desviación estándar muestral es", np.std(x,ddof=1))
    except:
        print("Cuidado con lo que escribe, solo se admiten valores numéricos")
    return

In [153]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

In [154]:
def txttomtx(x):
    L=x.split()
    L=[float(i) for i in L]
    e=np.sqrt(len(L))
    d=int(e)
    k=0
    M=np.zeros((d,d))
    for i in range(d):
        for j in range(d):
            M[i,j]=L[k]
            k=k+1
    return M

In [155]:
txttomtx("1 2 3 4")

array([[1., 2.],
       [3., 4.]])

In [156]:
M=txttomtx("1 2 3 4")

In [157]:
M

array([[1., 2.],
       [3., 4.]])

In [158]:
np.linalg.det(M)

-2.0000000000000004

In [159]:
def matrizopun(x,y):
    try:
        M=txttomtx(x)
        M2=txttomtx(y)
        SM=M+M2
        print("La suma es:",SM)
    except:
        print("Cuidado con lo que escribe, solo se admiten valores numéricos")
    return

In [160]:
interact(matrizopun,x="1 2 3 4",y="1 2 3 4")

interactive(children=(Text(value='1 2 3 4', description='x'), Text(value='1 2 3 4', description='y'), Output()…

<function __main__.matrizopun(x, y)>