# Numpy - Computación numérica

:::::{important} Para tener presente


[Numpy](https://numpy.org/) es la librería central para la computación científica en Python.


````{tabbed} ¿Para qué?

:::{admonition} Importante
:class: tip
Permite acceder a una gran cantidad de funciones matemáticas y crear arreglos multidimensionales de alta eficiencia
:::
````

````{tabbed} ¿Tiene documentación?

:::{admonition} Por supuesto:
:class: tip 
Es un paquete fácil de utilizar y posee una de las [documentaciones](https://numpy.org/doc/) más robustas de Python, quizás es uno de los paquetes más usados.
:::
````

````{tabbed} Sobre su poasado

:::{admonition}  ¿De dónde viene?
:class: tip 
Su ancestro es un paquete llamado Numeric, creado por [Jim Hugunin](https://en.wikipedia.org/wiki/Jim_Hugunin) y en 2005, con la incorporación de Numarray y varias modificaciones, [Travis Oliphant](https://en.wikipedia.org/wiki/Travis_Oliphant) lo transforma en Numpy.
:::
````
:::::

En cuadernos anteriores ya hemos trabajado con algunos paquetes, por ejemplo `math`. Cuando se importan los paquetes y no se les asigna ningún alias, para usar una función de dicho paquete debe digitarse el nombre del paquete seguido de un punto y el nombre de la función, constante, etc., como por sigue:

In [1]:
import math 

In [2]:
math.pi

3.141592653589793

Cuando se le pone un alias al paquete, se debe digitar el alias, seguido del punto y luego la función o constante:

In [3]:
import math as loquequiera

In [4]:
loquequiera.pi

3.141592653589793

Para conocer la ayuda que tienen las funciones o constantes, podemos emplear el siguiente código:

In [5]:
?math.pi

Type:        float
String form: 3.141592653589793
Docstring:   Convert a string or number to a floating point number, if possible.


Si queremos conocer todos los atributos o métodos que tiene el paquete, empleamos la función `dir`:

In [6]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

Ahora que ya recordamos como invocar paquetes, importaremos el paquete `numpy` con su alias `np`:

In [8]:
import numpy as np

Si queremos conocer la ayuda del paquete y el contenido del mismo, recuerda utilizar los siguientes comandos:
```python
?np
dir(np)
```

## Conceptos básicos

El objeto más importante de numpy es el arreglo (`array`) multidimensional homogéneo, es decir, una tabla de elementos del mismo tipo, indexados por una tupla de enteros no negativos. En numpy las dimensiones del arreglo las llamaremos ejes (axes).

### Ejemplo

Un elemento en $\mathbb{R}^n$ es un arreglo $n$-dimensional con un único eje:



In [13]:
V = np.array([2,1,4])
print(V)

[2 1 4]


In [15]:
W = np.array([3,1,2])
W

array([3, 1, 2])

Con los arreglos de `numpy` podemos hacer operaciones, como por ejemplo sumarlos y restarlos elemento a elemento:

In [17]:
print(V+W)

[5 2 6]


In [18]:
print(V-W)

[-1  0  2]


El contenido de los arreglos no necesariamente, debe ser numérico, pueden ser cadenas de texto o variables booleanas, etc.

In [23]:
np.array(['a',1])

array(['a', '1'], dtype='<U21')

In [24]:
BV=np.array([True,False,True])
print(BV)

[ True False  True]


Cuando vimos listas multidimensionales, definimos lo que es una matriz. En este paquete tenemos un concepto análogo de lo que es una matriz de tamaño $n\times m$, es un arreglo de dos ejes:

In [25]:
M=np.array([[1,0,1],[0,1,0],[2,1,3]])
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


Sobre este tipo de arreglos tenemos algunos métodos muy interesantes, como lo son: `dtype`, `shape`, `cumsum()` y `ndim`:

In [26]:
M.dtype
#Para conocer el tipo de dato con el que estamos trabajando

dtype('int64')

In [27]:
M.shape
#Para conocer las dimensiones del arreglo

(3, 3)

In [30]:
CS=M.cumsum()
CS
#Crea un arreglo, en el que la entrada i es la suma de todos los elementos hasta él en el arreglo

array([1, 1, 2, 2, 3, 3, 5, 6, 9])

En casos más generales, podríamos trabajar con un arreglo de matrices, o mejor conocido como tensor:

In [31]:
T=np.array([[[[1,2,1,4],[3,2,4,1],[4,2,3,1]],[[1,2,3,1],[0,1,2,3],[1,4,5,6]]],[[[2,3,4,1],[1,1,2,1],[0,1,1,2]],[[1,2,3,1],[0,1,1,1],[2,1,3,1]]]])
print(T)

[[[[1 2 1 4]
   [3 2 4 1]
   [4 2 3 1]]

  [[1 2 3 1]
   [0 1 2 3]
   [1 4 5 6]]]


 [[[2 3 4 1]
   [1 1 2 1]
   [0 1 1 2]]

  [[1 2 3 1]
   [0 1 1 1]
   [2 1 3 1]]]]


In [32]:
T.shape

(2, 2, 3, 4)

In [33]:
T.dtype

dtype('int64')

In [34]:
T.ndim

4

La exploración de elementos que conforman al arreglo es similar a la de las listas de Python, con la salvedad de que en la matriz, o el tensor no tenemos una lista de listas, motivo por el cual podemos llamar a los elementos de una manera adicional:

In [35]:
V

array([2, 1, 4])

In [36]:
V[1]

1

In [37]:
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [38]:
M[1,1]

1

In [39]:
#El comando anterior equivale a:
M[1][1]

1

In [40]:
print(T)

[[[[1 2 1 4]
   [3 2 4 1]
   [4 2 3 1]]

  [[1 2 3 1]
   [0 1 2 3]
   [1 4 5 6]]]


 [[[2 3 4 1]
   [1 1 2 1]
   [0 1 1 2]]

  [[1 2 3 1]
   [0 1 1 1]
   [2 1 3 1]]]]


In [41]:
T[1]

array([[[2, 3, 4, 1],
        [1, 1, 2, 1],
        [0, 1, 1, 2]],

       [[1, 2, 3, 1],
        [0, 1, 1, 1],
        [2, 1, 3, 1]]])

In [42]:
T[1,0]
#T[1][0]

array([[2, 3, 4, 1],
       [1, 1, 2, 1],
       [0, 1, 1, 2]])

In [43]:
T[1,0,2]
#T[1][0][2]

array([0, 1, 1, 2])

In [44]:
#Los tensores pueden contener texto:
TT=np.array([[[1,0,1],[0,1,0]],[[1,"0",3],[1,2,5]]])

In [45]:
TT

array([[['1', '0', '1'],
        ['0', '1', '0']],

       [['1', '0', '3'],
        ['1', '2', '5']]], dtype='<U21')

In [46]:
TT.shape

(2, 2, 3)

In [50]:
TT[1,1,1]
#TT[1][1][1]

'2'

Para extraer submatrices, podemos usar también índices de sublistas:

In [51]:
M2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
M2[:2,1:3]
#Tomamos los elementos de las filas 0 y 1
#que estén en las columnas 1 y 2

array([[2, 3],
       [6, 7]])

In [53]:
T=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32],[33,34,35,36]]])
print(T)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


Ahora extraeremos de las dos primeras matrices, lo que esté desde la fila 1 en adelante y lo que esté en las columnas 1 y 2.

In [54]:
T[:2,1:,1:3]

array([[[ 6,  7],
        [10, 11]],

       [[18, 19],
        [22, 23]]])

También podemos extraer elementos utilizando listas así:
```python
nombre_del_arreglo[[índices_de_filas],[índices_de_columnas]]
```

In [56]:
#Recordemos:
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
M2[[0,2],[1,3]]

array([ 2, 12])

Ahora extraeremos los valores 1,6,11 y 8 de la matriz M2:

In [59]:
M2[[0,1,2,1],[0,1,2,3]]

array([ 1,  6, 11,  8])

Los elementos se pueden repetir, por ejemplo:

In [61]:
M2[:,[0,1,2,2,1,1,2,2]]

array([[ 1,  2,  3,  3,  2,  2,  3,  3],
       [ 5,  6,  7,  7,  6,  6,  7,  7],
       [ 9, 10, 11, 11, 10, 10, 11, 11]])

Si deseamos extraer filas:

In [62]:
M2[np.array([0,2])]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Si lo que queremos extraer son columnas:

In [63]:
M2[:,np.array([2,0])]

array([[ 3,  1],
       [ 7,  5],
       [11,  9]])

Recordemos algunos de los comandos vistos de `numpy`:

* `.ndim` (número de ejes del arreglo)

In [64]:
V.ndim

1

In [65]:
M.ndim

2

In [66]:
T.ndim

3

* `.shape` (La dimensión del arreglo. Obtenemos una tupla de enteros)

In [67]:
V.shape

(3,)

In [68]:
M.shape

(3, 3)

In [69]:
T.shape

(3, 3, 4)

* `.size` (El número total de elementos que conforman al arreglo)

In [70]:
V.size

3

In [71]:
T.size

36

In [72]:
M.size

9

In [73]:
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


* `.concatenate` (concatena dos matrices, bien sea por filas o columnas)

In [75]:
np.concatenate((M,M),axis=0)
#Concatena por filas

array([[1, 0, 1],
       [0, 1, 0],
       [2, 1, 3],
       [1, 0, 1],
       [0, 1, 0],
       [2, 1, 3]])

In [74]:
np.concatenate((M,M),axis=1)
#Concatena por columnas

array([[1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [2, 1, 3, 2, 1, 3]])

In [78]:
N=np.concatenate((M,np.array([[0],[0],[0]])),axis=1)
N

array([[1, 0, 1, 0],
       [0, 1, 0, 0],
       [2, 1, 3, 0]])

Podemos intercambiar filas o columnas, seleccionando el orden que deseamos en la sublista:

In [79]:
N[:,[0,1,3,2]]

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [2, 1, 0, 3]])

* `.dtype` (el tipo de lementos en el arreglo)

In [80]:
M.dtype

dtype('int64')

In [81]:
A=np.array([3<2,2<3,4<5])
print(A)

[False  True  True]


In [82]:
A.dtype

dtype('bool')

In [83]:
TT2=np.array([A,V])
print(TT2)

[[0 1 1]
 [2 1 4]]


In [84]:
TT2.dtype

dtype('int64')

## Creación de algunos arreglos clásicos

Tenemos la oportunidad de utilizar algunas funciones de Numpy para generar arreglos y matrices ampliamente utilizadas:


In [85]:
ceros=np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [86]:
unos=np.ones((2,2,3))
print(unos)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [87]:
constante=np.full((4,3),5)
print(constante)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [88]:
constante2=np.full((4,3),5<2) #Creamos una matriz de 4x3 llena de False
constante2[1,1]=True #Asignamos el valor True a la entrada
print(constante2)

[[False False False]
 [False  True False]
 [False False False]
 [False False False]]


In [89]:
constante3=np.full((4,3),"Hola")
print(constante3)

[['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']]


In [90]:
identidad=np.eye(6,5)
print(identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


Unas matrices muy particulares son las que tienen su contenido generado de manera aleatoria:

In [91]:
aleatoria = np.random.random((2,2))  
print(aleatoria) 

[[0.24891508 0.15704794]
 [0.11322466 0.93719025]]


In [ ]:
?np.random

## Operaciones entre matrices
Las matrices son un objeto que se abordará profundamente en el curso de Álgebra Lineal, pero te presentaremos algunas de sus operaciones ya que siguen las ideas que hemos visto en las listas y en los arreglos:

In [93]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
y = np.array([[7,8,9],[9,8,7]])
z=np.array([[1,1],[2,1]])

In [94]:
print(x)
print(y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[7 8 9]
 [9 8 7]]
[[1 1]
 [2 1]]


La suma entre matrices, se realiza de la misma forma en que se hace con las listas, elemento a elemento:

In [95]:
print(x + y)

[[ 8. 10. 12.]
 [13. 13. 13.]]


Del mismo modo ocurre con la resta:

In [16]:
print(x - y)

[[-6. -6. -6.]
 [-5. -3. -1.]]


Algunas operaciones no tan comunes son las siguientes:

In [96]:
print(x*y) #multiplicación elemento a elemento

[[ 7. 16. 27.]
 [36. 40. 42.]]


In [97]:
print(x / y) #división elemento a elemento

[[0.14285714 0.25       0.33333333]
 [0.44444444 0.625      0.85714286]]


In [98]:
print(y)
print(np.sqrt(y))  #raíz cuadrada elemento a elemento

[[7 8 9]
 [9 8 7]]
[[2.64575131 2.82842712 3.        ]
 [3.         2.82842712 2.64575131]]


In [99]:
print(np.transpose(y)) #transpuesta (las filas se vuelven columnas)

[[7 9]
 [8 8]
 [9 7]]


In [100]:
print(y.T) #transpuesta

[[7 9]
 [8 8]
 [9 7]]


(m,k) @ (k,n)=(m,n)

In [22]:
print(x@np.transpose(y)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [23]:
print(np.transpose(y)@x)

[[43. 59. 75.]
 [40. 56. 72.]
 [37. 53. 69.]]


In [24]:
print(x.dot(y.T)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [25]:
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
print(np.sum(x))   #suma de todos los elementos
print(np.sum(x, axis=0))  #suma de elementos por columnas
print(np.sum(x, axis=1))   #suma de elementos por filas

21.0
[5. 7. 9.]
[ 6. 15.]


Mas funciones [aquí](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

## Operaciones especiales

En ocasiones tenemos que hacer algunas operaciones que no tienen en cuenta la forma de las matrices o que involucran matrices de diferentes tamaños. Aquí algunos ejemplos:

In [102]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Para sumar la misma constante a cada elemento del arreglo:

In [103]:
print(x+10)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [104]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array(np.transpose([[1, 0, 1,1]]))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1]
 [0]
 [1]
 [1]]


In [105]:
x+v

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [106]:
x+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

* Suma de un vector a una fila

In [107]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [108]:
x[0]=x[0]+v
print(x)

[[ 2  2  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Multiplicar una fila por un número real (escalar)

In [109]:
x[0]=x[0]*2
print(x)

[[ 4  4  8]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Intercambiar filas (empleando una variable auxiliar)

In [110]:
fc=x.copy()
x[1]=x[0]
x[0]=fc[1]
print(x)


[[ 4  5  6]
 [ 4  4  8]
 [ 7  8  9]
 [10 11 12]]


### Operaciones entre matrices de diferente tamaño (Broadcasting)

**NumPy** transforma los arreglos involucrados para que tengan el mismo tamaño y, por tanto, puedan someterse a las operaciones por elementos sin generar excepciones.

In [111]:
a = np.arange(0.2, 40.2, 10.5)
a.shape

(4,)

In [112]:
print(a)

[ 0.2 10.7 21.2 31.7]


In [113]:
a = a[:, np.newaxis]  #Adicionamos un eje
print(a.shape)
a

(4, 1)


array([[ 0.2],
       [10.7],
       [21.2],
       [31.7]])

In [114]:
b = np.array([0, 1, 2])
print(b)

[0 1 2]


Ahora, sumaremos a cada columna de la matriz *a* el arreglo *b* definido en la línea anterior:

In [115]:
a+b

array([[ 0.2,  1.2,  2.2],
       [10.7, 11.7, 12.7],
       [21.2, 22.2, 23.2],
       [31.7, 32.7, 33.7]])

Las siguientes matrices sirven como otro ejemplo para este tipo de operaciones:

In [120]:
A=np.array([[0,1],[1,2]])
B=np.array([[2,1],[1,2]])

In [122]:
A.shape

(2, 2)

In [124]:
A= A[:,:, np.newaxis] 

In [125]:
A.shape

(2, 2, 1)

In [126]:
A

array([[[0],
        [1]],

       [[1],
        [2]]])

In [55]:
A+B

array([[[2, 1],
        [2, 3]],

       [[3, 2],
        [3, 4]]])

Nota que a la matriz *B* se le ha sumado en cada columna, la columna [0,1] y luego [1,2].

# Herramientas interactivas `ipywidgets`

Otro paquete que será transversal en este curso y nos permitira crear interfaces interesantes para nuestros estudiantes es [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/). Para instalar desde el cuaderno escriba:

```Python
!pip install ipywidgets
```

In [129]:
#Debemos habilitar la extensión en nuestro entorno:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK


Importemos el paquete

In [137]:
from ipywidgets import interact
import ipywidgets as widgets

La herramienta más básica de este paquete es la función `interact`. En el siguiente ejemplo veremos su utilidad:

In [130]:
def f(x):
    print("El valor que escogió es", x)
    return x

In [131]:
f(4)

El valor que escogió es 4


4

In [138]:
interact(f, x=1.2)

interactive(children=(FloatSlider(value=1.2, description='x', max=3.5999999999999996, min=-1.2), Output()), _d…

<function __main__.f(x)>

In [139]:
interact(f, x=True)

interactive(children=(Checkbox(value=True, description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.f(x)>

In [140]:
interact(f, x={0:'Elemento 1',1:'Elemento 2'})

interactive(children=(Dropdown(description='x', options={0: 'Elemento 1', 1: 'Elemento 2'}, value='Elemento 1'…

<function __main__.f(x)>

In [141]:
interact(f, x='Soy interactivo')

interactive(children=(Text(value='Soy interactivo', description='x'), Output()), _dom_classes=('widget-interac…

<function __main__.f(x)>

Notemos que cada vez que se cambia el argumento de la función, el elemento interactivo cambia de inmediato, sin necesidad que nosotros lo indiquemos.

Veamos otro par de ejemplos:

In [132]:
def g(x):
    y=x+5
    print(x,"+",5,"=",y)
    return y

In [133]:
g(8)

8 + 5 = 13


13

In [150]:
interact(g, x=1.2)
#Objeto interactivo: Slider tipo float

interactive(children=(FloatSlider(value=1.2, description='x', max=3.5999999999999996, min=-1.2), Output()), _d…

<function __main__.g(x)>

In [152]:
interact(g, x=1)
#Objeto interactivo: Slider tipo int

interactive(children=(IntSlider(value=1, description='x', max=3, min=-1), Output()), _dom_classes=('widget-int…

<function __main__.g(x)>

In [134]:
def nombrelargoocorto(t):
    if len(t)>=7:
        print(t+" es un nombre muy largo")
        z="largo"
    else:
        print(t+" es un nombre corto")
        z="corto"
    return z

In [153]:
nombrelargoocorto("Benjamin")

Benjamin es un nombre muy largo


'largo'

In [154]:
interact(nombrelargoocorto, t="Pepito")
#Objeto interactivo: Caja de texto

interactive(children=(Text(value='Pepito', description='t'), Output()), _dom_classes=('widget-interact',))

<function __main__.nombrelargoocorto(t)>

In [157]:
interact(nombrelargoocorto, t=["Pepito","Luis","Gustavo","Felipe"])
#Objeto interactivo: Menú desplegable

interactive(children=(Dropdown(description='t', options=('Pepito', 'Luis', 'Gustavo', 'Felipe'), value='Pepito…

<function __main__.nombrelargoocorto(t)>

Los elementos que permiten la interacción con el usuario son los widgets, una lista completa de ellos se encuentra [aquí.](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html)

A continuación hacemos un cambio sobre el widget:

In [155]:
interact(f, x=widgets.IntText(
    value=7,
    description='Escriba un número: ',
    disabled=False
));

interactive(children=(IntText(value=7, description='Escriba un número: '), Output()), _dom_classes=('widget-in…

In [ ]:
interact()

## Una primera aplicación

Ya que conocemos algo de Numpy y ipywidgets vamos a crear un ejemplo muy sencillo para calcular algunos estadísticos elementales de una lista de valores:

In [144]:
def estadisticos(x):
    L=x.split()
    L=[float(i) for i in L]        
    x=np.array(list(L))
    print("La media es", np.mean(x))
    print("La mediana es", np.median(x))
    print("La varianza poblacional es", np.var(x))
    print("La varianza muestral es", np.var(x,ddof=1))
    print("La desviación estándar poblacional es", np.std(x))
    print("La desviación estándar muestral es", np.std(x,ddof=1))
    return

In [145]:
estadisticos("1 2 3")

La media es 2.0
La mediana es 2.0
La varianza poblacional es 0.6666666666666666
La varianza muestral es 1.0
La desviación estándar poblacional es 0.816496580927726
La desviación estándar muestral es 1.0


Evalue los estadísticos del conjunto de datos [1,1,2,3] y compruebelo con la herramienta:

In [146]:
estadisticos("1 2 3 4 5 7 8 3 1 3 4 1 3 4 8 0 9")

La media es 3.8823529411764706
La mediana es 3.0
La varianza poblacional es 6.927335640138407
La varianza muestral es 7.360294117647058
La desviación estándar poblacional es 2.6319832142584816
La desviación estándar muestral es 2.7129861993100994


In [147]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

In [148]:
def estadisticos(x):
    try:
        L=x.split()
        L=[float(i) for i in L]        
        x=np.array(list(L))
        print("La media es", np.mean(x))
        print("La mediana es", np.median(x))
        print("La varianza poblacional es", np.var(x))
        print("La varianza muestral es", np.var(x,ddof=1))
        print("La desviación estándar poblacional es", np.std(x))
        print("La desviación estándar muestral es", np.std(x,ddof=1))
    except:
        print("Cuidado con lo que escribe, solo se admiten valores numéricos")
    return

In [149]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

## Ejercicio
1. Crea una función, para luego hacer un elemento interactivo con ella, de tal modo que se digite una cantidad que sea el cuadrado de un número entero de datos y esta lo escriba como una matriz del tamaño adecuado, es decir, si se digitan 4 elementos, la respuesta de la función debe ser una matriz de tamaño 2x2.